filters:
  germline:
    description: "Hard filter CNV"
    expression: "(VEP:gnomAD_AF < 0.05)"
    soft_filter: "False"


(SVTYPE:)

ALT=<ID=DEL,Description="Deletion">
ALT=<ID=DUP,Description="Duplication">
ALT=<ID=INS,Description="Insertion">
ALT=<ID=INS:ME,Description="Mobile element insertion of unspecified ME class">
ALT=<ID=INS:ME:ALU,Description="Alu element insertion">
ALT=<ID=INS:ME:LINE1,Description="LINE1 element insertion">
ALT=<ID=INS:ME:SVA,Description="SVA element insertion">
ALT=<ID=INS:UNK,Description="Sequence insertion of unspecified origin">
ALT=<ID=CNV,Description="Copy Number Polymorphism">


ALT=<ID=BND,Description="Translocation">
ALT=<ID=CPX,Description="Complex SV">
ALT=<ID=CTX,Description="Reciprocal chromosomal translocation">
ALT=<ID=INV,Description="Inversion">
